app:
  storage:
    s3:
      bucket: videos
      inputPrefix: input
      region: us-east-1
      endpoint: http://localhost:4566
      pathStyle: true
      createBucketIfMissing: true
      accessKey: test
      secretKey: test
  messaging:
    sqs:
      queueName: jobs-events.fifo
      region: us-east-1
      endpoint: http://localhost:4566
      createQueueIfMissing: true
      fifo: true
      contentBasedDeduplication: true
      defaultDelaySeconds: 0
      messageGroupStrategy: user
      staticMessageGroupId: jobs
      consumer:
        queueName: jobs-ready     # ou defina queueUrl diretamente
        region: us-east-1
        endpoint: http://localhost:4566
        maxMessages: 10
        waitTimeSeconds: 10
        visibilityTimeoutSeconds: 60    # aplica ao receive (opcional)
        extendVisibilitySeconds: 120    # estende periodicamente durante o processamento (0=desabilita)
        pollIntervalMillis: 1000
        concurrency: 4
  cognito:
    userPoolId: ${COGNITO_USER_POOL_ID:us-east-1_IjXtmykzZ}
    clientId: ${COGNITO_CLIENT_ID:27qrpbh2oi5cbbletblkh7b4ub}
    region: ${COGNITO_REGION:us-east-1}
    jwkUrl: ${COGNITO_JWK_URL:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_IjXtmykzZ/.well-known/jwks.json}

spring:
  profiles:
    active: ${PROFILE:DEV}
  servlet:
    multipart:
      max-file-size: 10MB       # tamanho máximo de UM arquivo
      max-request-size: 10MB   # soma de todos os arquivos + campos do form
      file-size-threshold: 5MB  # acima disso, grava em disco (não só memória)
  application:
    name: updown
  docker:
    compose:
      file: ./run/docker-compose.yml
  config:
    import: optional:file:.env-dev[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/updown}
    username: ${SPRING_DATASOURCE_USERNAME:updown_user}
    password: ${SPRING_DATASOURCE_PASSWORD:updown_password}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none # Flyway gerencia
    show-sql: true
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger
      use-root-path: true
server:
  jetty:
    max-http-form-post-size: 10MB