apiVersion: v1
kind: Service
metadata:
  name: updown
  namespace: framegenerator
spec:
  type: LoadBalancer
  selector:
    app: updown
  ports:
    - name: http
      port: 80
      targetPort: 8080